import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const manrope = Manrope({
  variable: "--font-sans",
  subsets: ["latin"],
  weight: ["300", "400", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "overflow-hidden", manrope.variable, "font-sans")}
    >
      <body className="h-full overflow-hidden">
        <main className="h-full min-h-dvh not-only:overflow-hidden">
          {children}
        </main>
      </body>
    </html>
  );
}
